event_inherited()

f_sprite = spr_face_susie // -1 if each is specified, a sprite index if expressions are img indexes

face_expressions={
	angry: 0,
	angry_b: 1,
	angry_c: 2,
	annoyed: 3,
	annoyed_down: 4,
	bangs_neutral: 5,
	bangs_smile: 6,
	bangs_teeth: 7,
	blush: 8,
	closed_grin: 9,
	glasses: 10,
	nervous: 11,
	nervous_side: 12,
	neutral: 13,
	neutral_side: 14,
	sad: 15,
	sad_frown: 16,
	shock: 17,
	shock_down: 18,
	shock_nervous: 19,
	shy: 20,
	shy_stupid: 21,
	shy_down: 22,
	sincere: 23,
	sincere_smile: 24,
	small_smile: 25,
	smile: 26,
	smirk: 27,
	surprise: 28,
	surprise_frown: 29,
	surprise_smile: 30,
	sus_nervous: 31,
	suspicious: 32,
	teeth: 33,
	teeth_b: 34,
	teeth_smile: 35,
}