event_inherited()
f_sprite = spr_face_noelle // -1 if each is specified, a sprite index if expressions are img indexes

face_expressions = {
    afraid: 0,
    afraid_b: 1,
    blush: 2,
    blush_big_smile: 3,
    blush_finger: 4,
    blush_question: 5,
    blush_side: 6,
    blush_smile: 7,
    blush_smile_closed: 8,
    blush_surprise: 9,
    blush_surprise_smile: 10,
    confused: 11,
    confused_surprise: 12,
    confused_surprise_b: 13,
    dejected: 14,
    down: 15,
    down_smile: 16,
    frown: 17,
    neutral: 18,
    question: 19,
    sad: 20,
    sad_b: 21,
    sad_side: 22,
    sad_smile: 23,
    sad_smile_b: 24,
    shock: 25,
    shock_b: 26,
    silly: 27,
    smile: 28,
    smile_alt: 29,
    smile_closed: 30,
    smile_closed_b: 31,
    smile_side: 32,
    surprise_frown: 33,
    surprise_frown_b: 34,
    surprise_smile: 35,
    surprise_smile_b: 36,
    upset: 37,
    upset_down: 38,
    upset_side: 39,
    what: 40,
    what_smile: 41,
    what_smile_b: 42
};
